config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :tweets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :tweet, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :current_password, :password, :password_confirmation)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all.order("created_at DESC")
    @tweet = Tweet.new
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.build
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = current_user.tweets.build(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to root_path, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    if current_user == @tweet.user
      @tweet.destroy
      respond_to do |format|
        format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to tweets_url, alert: 'You are not authorized to delete this tweet.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:tweet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://kit.fontawesome.com/fcf9201011.js" %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <header>
      <nav class="navbar is-info" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <a class="navbar-item" href="/">
            TWITTER
          </a>

          <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="buttons">
                <% if user_signed_in? %>
                  <div class="dropdown is-hoverable is-right pb-4">
                    <div class="dropdown-trigger">
                      <figure class="media-left" aria-haspopup="true" aria-controls="dropdown-menu">
                        <div class="columns">
                          <p class="image is-64x64 column">
                            <img style="max-height: unset;" alt class="is-rounded" src="https://bulma.io/images/placeholders/64x64.png">
                          </p>
                          <p class="column" style="white-space: nowrap;">
                            <span><%= current_user.name %></span> <br>
                            <small>@<%= current_user.username %></small>
                          </p>
                        </div>
                      </figure>
                    </div>
                    <div class="dropdown-menu" id="dropdown-menu" role="menu">
                      <div class="dropdown-content">
                        <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
                      </div>
                      <div class="dropdown-content">
                        <%= link_to destroy_user_session_path, method: :delete, data: { confirm: "Are you sure you want to logout?" }, class: "dropdown-item" do %>
                          <strong>Logout</strong><span class="icon"><i class="fas fa-sign-out-alt"></i></span>
                        <% end %>
                      </div>
                    </div>
                  </div>
                <% else %>
                    <%= link_to new_user_registration_path, class: "button is-link is-rounded" do %>
                      <strong>Sign up</strong>
                    <% end %>
                    <%= link_to "Log in", new_user_session_path, class: "button is-light is-rounded" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>

app/views/tweets/_feed.html.erb
<div class="column is-half">
  <% if user_signed_in? %>
  <article class="media box">
    <figure class="media-left">
      <p class="image is-64x64">
        <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name, class: "is-rounded") %>
      </p>
    </figure>

    <div class="media-content">
      <%= render 'tweets/form' %>
    </div>
  </article>
  <% end %>

  <div class="tweet-list panel">
    <% @tweets.each do |tweet| %>
      <div class="panel-block">
        <article class="media p-4 is-fullwidth">
          <div class="media-left">
            <figure class="image is-64x64">
              <%= gravatar_image_tag(tweet.user.email, size: 64, alt: tweet.user.name, class: "is-rounded") %>
            </figure>
          </div>
          <div class="media-content">
            <div class="content">
              <strong><%= tweet.user.name %></strong>
              <span class="is-light">.</span>
              <small>@<%= tweet.user.username %></small>
              <span class="is-light">.</span>
              <small><%= time_ago_in_words(tweet.created_at) %></small>
              <%= link_to tweet do %>
                <p class="has-text-dark"><%= tweet.tweet %></p>
              <% end %>
            </div>

            <nav class="level">
              <div class="level-left">
                <div class="level-item mr-4">
                  <div>
                    <a href="#">
                      <span class="icon"><i class="far fa-comment-alt" aria-hidden="true"></i></span>
                    </a>
                  </div>
                </div>

                <div class="level-item mx-5">
                  <div>
                    <a href="#">
                      <span class="icon"><i class="fas fa-retweet" aria-hidden="true"></i></span>
                    </a>
                  </div>
                </div>

                <div class="level-item ml-4">
                  <div>
                    <a href="#">
                      <span class="icon"><i class="far fa-heart" aria-hidden="true"></i></span>
                    </a>
                  </div>
                </div>
              </div>
              <div class="level-right">
                <div class="level-item">
                  <div>
                    <a href="#">
                      <span class="icon"><i class="far fa-share-square" aria-hidden="true"></i></span>
                    </a>
                  </div>
                </div>
              </div>
            </nav>
          </div>
          <% if user_signed_in? and tweet.user == current_user %>
          <div class="media-right">
            <div class="dropdown is-hoverable is-right">
              <div class="dropdown-trigger">
                <button class="button is-white" aria-haspopup="true" aria-controls="dropdown-menu">
                  <span class="icon"><i class="fas fa-ellipsis-h"></i></span>

                </button>
              </div>
              <div class="dropdown-menu" id="dropdown-menu" role="menu">
                <div class="dropdown-content">
                  <%= link_to edit_tweet_path(tweet), class: "dropdown-item" do %>
                    <p>
                      <span class="icon"><i class="fas fa-pencil-alt" aria-hidden="true"></i> </span>
                      Edit Tweet
                    </p>
                  <% end %>
                </div>
                <div class="dropdown-content">
                  <%= link_to tweet, method: :delete, data: {confirm: "Are you sure you want to delete this tweet?"}, class: "dropdown-item" do %>
                    <p class="has-text-danger">
                      <span class="icon"><i class="fas fa-trash-alt is-danger" aria-hidden="true"></i></span>
                      Delete tweet
                    </p>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        </article>
      </div>
    <% end %>
  </div>
</div>

app/views/tweets/_form.html.erb
<%= simple_form_for(@tweet) do |f| %>
  <% if f.error_notification %>
    <div class="notification is-danger is-light">
      <p><%= f.error_notification %></p>
    </div>
  <% end %>
  <div class="field">
    <div class="control">
      <%= f.input :tweet, label: "Tweet your thought", input_html: { class: "textarea"}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new tweet ..." %>
    </div>
    <%= f.button :submit, class: "button is-info is-rounded mt-4" %>
  </div>
<% end %>

app/views/tweets/_profile.html.erb
<div class="column is-one-quarter">
	<nav class="panel is-light">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
						<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name, class: "is-rounded") %>
					</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p>
							<strong><%= current_user.name %></strong><br />
							<small><%= current_user.username %></small>
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Tweeets</p>
						<p class="title is-6"><%= current_user.tweets.count %></p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Following</p>
						<p class="title is-6">123</p>
					</div>
				</div>
					<div class="level-item has-centered-text">
					<div>
						<p class="heading">Followers</p>
						<p class="title is-6">465K</p>
					</div>
				</div>
			</div>
		</div>
	</nav>
</div>

app/views/tweets/_trends.html.erb
<div class="column">
  <div class="panel is-light">
    <p class="panel-heading">Top trends</p>

    <div class="panel-block">
      <div class="media">
        <div class="media-left">
          <a href="#" class="">#trend 1</a>
        </div>
      </div>
    </div>

    <div class="panel-block">
      <div class="media">
        <div class="media-left">
          <a href="#" class="">#trend 2</a>
        </div>
      </div>
    </div>

    <div class="panel-block">
      <div class="media">
        <div class="media-left">
          <a href="#" class="">#trend 3</a>
        </div>
      </div>
    </div>

    <div class="panel-block">
      <div class="media">
        <div class="media-left">
          <a href="#" class="">#trend 4</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tweets/_who_to_follow.html.erb
<div class="column is-3">
  <div class="panel is-light">
    <p class="panel-heading">Who to follow</p>

    <div class="panel-block">
      <article class="media">
        <figure class="media-left">
          <p class="image is-48x48">
            <img class="is-rounded" src="https://bulma.io/images/placeholders/48x48.png">
          </p>
        </figure>
        <div class="media-content">
          <div class="content">
            <p>
              <strong>Dipesh Bajgain</strong> <br>
              <small>@dipbazz</small>
            </p>
          </div>
        </div>
        <div class="media-right">
          <a href="#" class="button is-outlined is-link is-rounded is-small">follow</a>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <article class="media">
        <figure class="media-left">
          <p class="image is-48x48">
            <img class="is-rounded" src="https://bulma.io/images/placeholders/48x48.png">
          </p>
        </figure>
        <div class="media-content">
          <div class="content">
            <p>
              <strong>Dipesh Bajgain</strong> <br>
              <small>@dipbazz</small>
            </p>
          </div>
        </div>
        <div class="media-right">
          <a href="#" class="button is-outlined is-link is-rounded is-small">follow</a>
        </div>
      </article>
    </div>

    <div class="panel-block">
      <article class="media">
        <figure class="media-left">
          <p class="image is-48x48">
            <img class="is-rounded" src="https://bulma.io/images/placeholders/48x48.png">
          </p>
        </figure>
        <div class="media-content">
          <div class="content">
            <p>
              <strong>Dipesh Bajgain</strong> <br>
              <small>@dipbazz</small>
            </p>
          </div>
        </div>
        <div class="media-right">
          <a href="#" class="button is-outlined is-link is-rounded is-small">follow</a>
        </div>
      </article>
    </div>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Tweet</h1>
				<%= render 'form', tweet: @tweet %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', tweets_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/tweets/index.html.erb
<div class="container mt-5">
  <div class="columns">
    <% if user_signed_in? %>
      <%= render 'profile' %>
    <% else %>
      <%= render 'trends' %>
    <% end %>

    <%= render 'feed' %>
    <%= render 'who_to_follow' %>
  </div>
</div>

app/views/tweets/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Create a new Tweet</h1>
					<%= render 'form', tweet: @tweet %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', tweets_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
  <%= @tweet.tweet %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>